# k8s/deployment-demo.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5
  labels:
    app: yolo5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5
  template:
    metadata:
        labels:
          app: yolo5
    spec:
      containers:
      - name: server
        image: selotapetm/yolo-cicd-dev:0.0.4
---

apiVersion: v1
kind: Service
metadata:
  name: yolo5-svc
spec:
  selector:
    app: yolo5
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443